### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by krevedkin** [SMhero/calculator-react#1]
hey man i wanna know what will be if I try to calculate 2+2*2 all my schoolmates laughed at me after i said 8... i have no idea why... i need your calculator for get right result! Could you develop it for me? i've seen it started 4 month ago... any result?

**Comment by SMhero** [comment]
I've no idea when I'll continue my development. Stay tuned! 👨‍🚀

**Comment by krevedkin** [comment]
So sad my friend, so sad...
